# Config file for automatic testing at travis-ci.org

language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36

install:
- pip install -U wheel
- pip install -U tox
- pip install -U codecov

# command to run tests, e.g. python setup.py test
script: tox

addons:
  apt:
    packages:
      - language-pack-ru

after_success:
    - codecov

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: ivbeg
  on:
    tags: true
    repo: ivbeg/docx2csv
    condition: "$TOXENV == py36"
